# Generated by Django 3.1.3 on 2021-02-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=15)),
                ('product_price', models.IntegerField()),
                ('product_dec', models.CharField(max_length=50)),
                ('product_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
