# Generated by Django 3.1.3 on 2021-02-12 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
