# Generated by Django 3.1.3 on 2021-02-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210212_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_date',
        ),
    ]
