# Generated by Django 3.1.3 on 2021-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_cart_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dec',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=67),
        ),
    ]
