# Generated by Django 3.1.3 on 2021-02-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_eidt_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eidt_profile',
        ),
    ]
